### ISSUE TITLE
IMDB

### ISSUE THREAD

**Issue by fceller** [arangodb/example-datasets#3]
> i am Student at Technische Hochschule Mittelhessen and at the moment i am trying to use the graph part of ArangoDB. For that reason i've imported your dataset imdb but unlike you mention on github, there is no graph "imdb" created. I only get the two collections imdb_vertices and imdb_edges. I am really new to ArangoDB, so can you tell me please, if there is a possibility to create a new graph from the shell (which?)?

**Comment by dothebart** [comment]
I started out a little different. I've loaded the graph data like this
arangosh [_system]> require("internal").load("/local/home/me/ArangoDB-Data/Graphs/IMDB/import.js")

After waiting for a while, I now can see the graph (by default with two nodes) in the graph viewer.
Did you Follow
https://www.arangodb.com/2013/11/visualize-graphs-screencast/
?

**Comment by dgoogler** [comment]
I tried to load the graph the way you described but i get the following error:

"JavaScript exception in file 'path/to/file/ArangoDB-Data/Graphs/IMDB/import.js' at 57,21: TypeError: Cannot read property 'ensureFulltextIndex' of
! internal.processJsonFile("nodes.json", storeVertex);
!              ^
stacktrace: Error: cannot open file: No such file: No such file or directory
     at Error (native)
     at path/to/file/ArangoDB-Data/Graphs/IMDB/import.js:62:12
     at path/to/file/ArangoDB-Data/Graphs/IMDB/import.js:64:2
     at <shell command>:1:21"

However, I am able to find the collections and a graph named "imdb" as well. When I go to the settings of the graph, the vertex collections is empty. I add the imdb_vertices manually and save, but reopening the settings the field is empty again. When I want to display it there is the dialog "Sorry your graph seems to be empty". 
And I tried to follow the screencast but when I navigated to "Graphs" there was no possibility to configure the Graph Viewer.

The way I did the import yesterday (https://github.com/triAGENS/ArangoDB-Data/tree/master/Graphs/IMDB) I was able to see the collections but unlike as mentioned there I did not have the graph imdb.

**Comment by dgoogler** [comment]
And to add that: Both collections are empty when I import the way you suggested.

**Comment by dgoogler** [comment]
I got the problem solved. After following your suggestion I got two empty collections and the empty graph so I executed the import.sh and neither the collections nor the graph remained empty. Thank you!

**Comment by dgoogler** [comment]
I am sorry I have a new problem.
Following the screencast for visualizing graphs, I can view, create (nodes and edges), edit and delete, but nothing happens when I want to spot to explore the graph.

**Comment by sleto-it** [comment]
Hi - import.js and .sh scripts included in IMDB have been updated today again and the import has been tested with version 3.2.9

This issue is quite old - I think we can safely close it now - or can we do something else?

Thanks,

**Comment by dothebart** [comment]
Closing as fixed.
