### ISSUE TITLE
Error while loading imdb dataset

### ISSUE THREAD

**Issue by sowee15** [arangodb/example-datasets#7]
Hi,

I tried loading the imdb dataset to try out ArangoSearch. I'm on windows, so I CD'ed to the folder containing import.js, edges.json and nodes.json. From there I started arangosh, switched to my database and ran require("internal").load("import.js"). I found that the graph object returned by gm._create does not have a drop function or an addVertex function. g is indeed a Graph object though and the graph is created in my database. Is this a deprecated API as I'm running 3.4.

Thanks!

**Comment by Simran-B** [comment]
To drop a named graph, you need to call the `_drop()` function of the general-graph module:

    var gm = require('@arangodb/general-graph');
    gm._drop('imdb', true);

The graph object does not have this method.

Also see the shell script (you may install Git with Bash shell and use it to run the script under Windows):
https://github.com/arangodb/example-datasets/blob/master/Graphs/IMDB/import.sh

**Comment by dothebart** [comment]
https://github.com/arangodb/example-datasets/commit/ece77c9b056bd26c44ce0205b872256485ae0752 fixed this.
sorry for the late reply.
