### ISSUE TITLE
Windows import issues

### ISSUE THREAD

**Issue by undeadindustries** [arangodb/example-datasets#8]
I could have swore I posted this already. But I don't see it so posting "again" ..

Arango 3.4.1
Windows 10 pro amd64 latest build.

When trying to import IMDB I follow these steps:
1- cd into the IMDB folder.
2- run arangosh
3- require("internal").load("import.js")

There are 2 errors:

First error is that, no matter what, it says the graph already exists.
To fix, I remove this code:
```
try {
    g = gm._create(gName);
    g.drop();
  } catch (e) {

  }
```

Second error:
```
127.0.0.1:8529@_system> require("internal").load("import.js")
2019-01-22T18:12:16Z [2096] ERROR JavaScript exception in file 'import.js' at 32,7: TypeError: g.addVertex is not a function
2019-01-22T18:12:16Z [2096] ERROR !    g.addVertex(d._key, d);
2019-01-22T18:12:16Z [2096] ERROR !      ^
JavaScript exception in file 'import.js' at 32,7: TypeError: g.addVertex is not a function
!    g.addVertex(d._key, d);
!      ^
stacktrace: TypeError: g.addVertex is not a function
    at Function.storeVertex (import.js:32:7)
    at import.js:61:12
    at import.js:63:2
    at <shell command>:1:21

```

Please help! I'm a linux person, but I'm trying to make this project 100% Windows. (Just saying that because I've seen "just use bash" suggested in other issues...)

Thanks!

**Comment by Simran-B** [comment]
Sorry for the trouble! I couldn't figure out why the script is how it is yet, but it does not seem to be correct. It's possible that it was written for ArangoDB 2.x and uses no longer supported methods.

Graph objects don't have a `drop()` method apparently.

```js
try {
    g = gm._create(gName);
    g.drop();
```

To attempt a deletion of a named graph, the correct code should be `gm._drop(gName)`.

`addVertex()` and `addEdge()` don't exist either on the graph object. 

```js
    g.addVertex(d._key, d);
    if (d.genre) {
      var gK = toKey(d.genre);
      if (!genres[gK]) {
        genres[gK] = true;
        g.addVertex(gK, {label: d.genre});
      }
      g.addEdge(gK, d._key, null, "has_movie");
    }
  };

  var storeEdge = function(d) {
    var to = d._to;
    var from = d._from;

    delete d._key;
    try {
      g.addEdge(from, to, null, d["$label"], d);
    } catch (e) {
      console.log("Failed:", from, "->", to);
    }
  };
```

I believe it should be like this:

```js
    g[vName].save(d);
    if (d.genre) {
      var gK = toKey(d.genre);
      if (!genres[gK]) {
        genres[gK] = true;
        g[vName].save({ _key: gK, label: d.genre });
      }
      g[eName].save({ _from: vName + "/" + gK, _to: vName + "/" + d._key }) // ?
    }
  };

  var storeEdge = function(d) {
    delete d._key;
    try {
      g[eName].save( d ) // ?
    } catch (e) {
      console.log("Failed:", d._from, "->", d._to);
    }
  };
```

I'm not sure what the `has_movie` and `d["$label"]` are supposed to do.

**Comment by undeadindustries** [comment]
Ahh.  Are you just going to update it in the repo?

**Comment by dothebart** [comment]
https://github.com/arangodb/example-datasets/commit/ece77c9b056bd26c44ce0205b872256485ae0752 fixed this.
